### ISSUE TITLE
Scope detection

### ISSUE THREAD

**Issue by zyyv** [Efrice/vscode-quick-console#3]
Thank you so much for your project making it easier for me.

And I found some issues that could be optimized.
Is it possible to increase the detection of the scope, and it is not completely output on the next line.

<img width="368" alt="image" src="https://github.com/Efrice/vscode-quick-console/assets/42139754/5e881e3c-f908-45f1-a8ed-1755ab825452">

**Comment by Efrice** [comment]
Thanks, will fixed next version.
