### ISSUE TITLE
improved debug console format

### ISSUE THREAD

**Issue by Wxh16144** [Efrice/vscode-quick-console#5]
看到这个项目第一眼，我和你想法一样，之前也想写一个专属于自己的插件。但是从我之前的开发调试来看，希望可以加入一开关，以对象形式输出？

比如这个截图中：
<img width="776" alt="image" src="https://github.com/Efrice/vscode-quick-console/assets/32004925/2a889fac-721f-47f4-ae5a-26f9241490af">

以往我采用的都是代码片段的形式来满足需求。比如这样
https://github.com/Wxh16144/dotfiles/blob/2b2a30ed62c2bbc592a4941131aae3a500da1989/backup/Library/Application%20Support/Code/User/snippets/javascript.code-snippets#L3-L24

但是同事会吐槽有些 console 比较影响开发，可能就会使用到你这个插件提供的功能了，不知道我这个需求实现起来有没有难度，或者你有计划吗？可以指导一下我进行开发最好了。提前感谢你，谢谢

**Comment by Efrice** [comment]
Thanks, good idea! WIP...
